### ISSUE TITLE
nudepy fails to build with Python 3.9

### ISSUE THREAD

**Issue by fabaff** [hhatto/nude.py#23]
PyTypeObject has no member named tp_print, see https://bugs.python.org/issue39361

Origin: https://bugzilla.redhat.com/show_bug.cgi?id=1792967

**Comment by hhatto** [comment]
@fabaff Thanks for reporting.

fix in latest master.
re-generate skin_classifier.c with Cython 0.29.16.

**Comment by fabaff** [comment]
Thanks for fixing this.

**Comment by fabaff** [comment]
Could you please make a new release and publish it? This would include #22 as well which is still another open issue for the Fedora package. Thank you for your time and effort.

**Comment by hhatto** [comment]
nude.py version 0.5 just released.

https://pypi.org/project/nudepy/0.5/
